In [1]:
# 导入库
import numpy as np
import pandas as pd

In [2]:
# 读取csv文件
df = pd.read_csv('online_retail.csv')
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Unnamed: 8
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010/12/1 8:26,2.55,17850.0,United Kingdom,1454.0
1,536365,71053,WHITE METAL LANTERN,6,2010/12/1 8:26,3.39,17850.0,United Kingdom,135080.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010/12/1 8:26,2.75,17850.0,United Kingdom,406829.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010/12/1 8:26,3.39,17850.0,United Kingdom,NaN
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010/12/1 8:26,3.39,17850.0,United Kingdom,NaN

In [4]:
# 看数据几行几列
df.shape

(541909, 9)

In [5]:
# 看数据类型
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
 8   Unnamed: 8   3 non-null       float64
dtypes: float64(3), int64(1), str(5)
memory usage: 37.2 MB

In [9]:
# 查看重复行
print(df.duplicated().sum())

# 删除重复行
df = df.drop_duplicates()

# 查看剩余行数
print(df.shape)

0
(536641, 9)

In [10]:
# 查缺失数
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
Unnamed: 8     536638
dtype: int64

In [11]:
# 处理缺失值
df['CustomerID'] = df['CustomerID'].fillna('unknown')
df['Description'] = df['Description'].fillna('unknown')

# 确认缺失值
print(df.isnull().sum())

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID          0
Country             0
Unnamed: 8     536638
dtype: int64

In [13]:
# 文本日期转成日期格式
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

# 新增一列年月
df['YearMonth'] = df["InvoiceDate"].dt.to_period("M").astype(str)

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Unnamed: 8,YearMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,1454.0,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,135080.0,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,406829.0,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,NaN,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,NaN,2010-12

In [15]:
# 过滤异常值
# 只保留数量大于0的
df = df[df['Quantity']>0]

# 保留单价大于0的
df = df[df['UnitPrice']>0]

# 新增订单金额
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

print(df.shape)

(524878, 11)

In [16]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Unnamed: 8,YearMonth,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,1454.0,2010-12,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,135080.0,2010-12,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,406829.0,2010-12,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,NaN,2010-12,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,NaN,2010-12,20.34

In [17]:
# 导出数据
# 保存为新的CSV文件
df.to_csv("cleaned_data.csv", index=False, encoding="utf-8-sig")

print("清洗完成！已保存 cleaned_data.csv")

清洗完成！已保存 cleaned_data.csv